In [ ]:
%pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import tensorflow as tf

In [3]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.21.0


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

C:\Users\modin\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.973065  , -0.04147144,  0.4640681 ,  0.5867118 ,  0.75871736,
         0.47486207,  0.12018688,  0.62026274,  0.3835511 ,  0.42135972]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.15829411, 0.05739277, 0.0951503 , 0.10756569, 0.12775406,
        0.09618291, 0.06746282, 0.11123582, 0.0877894 , 0.09117214]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.3415034)

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - accuracy: 0.9137 - loss: 0.2942
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - accuracy: 0.9563 - loss: 0.1460
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - accuracy: 0.9677 - loss: 0.1092
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - accuracy: 0.9721 - loss: 0.0895
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - accuracy: 0.9756 - loss: 0.0759


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 4ms/step - accuracy: 0.9778 - loss: 0.0731


[0.07313182204961777, 0.9778000116348267]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.6834839e-09, 1.1137639e-09, 7.7603204e-07, 2.7571996e-05,
        2.8042162e-11, 4.6862354e-08, 5.4027881e-13, 9.9997115e-01,
        4.4307839e-08, 3.8722328e-07],
       [1.4166653e-07, 6.7234701e-05, 9.9978334e-01, 9.6973497e-05,
        3.5560961e-13, 5.0376542e-07, 6.1665942e-06, 3.9687313e-13,
        4.5579745e-05, 7.7898229e-13],
       [2.2528106e-07, 9.9577242e-01, 1.9493690e-04, 2.3972058e-05,
        8.3563296e-05, 1.3608406e-05, 2.6832902e-04, 3.1050327e-03,
        5.3607626e-04, 1.7721130e-06],
       [9.9985659e-01, 3.7509441e-08, 1.0808155e-05, 7.1292774e-08,
        1.8542022e-07, 7.1796997e-08, 6.8553651e-05, 6.2994695e-05,
        4.5926549e-10, 6.2045859e-07],
       [1.3404889e-06, 7.6046630e-10, 1.3981570e-05, 4.4116192e-07,
        9.9493176e-01, 1.6810114e-06, 7.3152173e-06, 9.6300384e-05,
        7.9255784e-07, 4.9462956e-03]], dtype=float32)>